# Configuraci0n del Volumen Persistente

apiVersion: v1                           # Version de la Api
kind: PersistentVolume                   # Tipo de Objeto: Volumen Persistente
metadata:
  name: master-pv                        # Nombre del Objeto
  labels:
    type: persistente                    # Etiqueta de tipo (Nada en especial)
spec:
  storageClassName: masterfiles          # Nombre de la clase
  capacity:
    storage: 10Gi                        # Capacidad en Gigas
  accessModes:
    - ReadWriteOnce                      # Modo de Acceso Lectura-Escritura, solo por un nodo al mismo tiempo
  hostPath:
    path: "/master"                      # Carpeta de Almacenamiento 